baseURL = 'https://www.nesono.com/'
languageCode = "en-us"
title = "nesono"
theme = "hugo-coder"
pygmentsStyle = "native"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 25
canonifyurls = true
author = "iss"
info = "tales from the past"

[markup.highlight]
style = "monokai"
